version: "3"
services:
  nginx:
    environment:
      LARAVEL_SERVER_NAME: localhost
    image: nginx:stable
    
    links:
      - app
    # mem_limit: 134217728b   # Available until version 2.1. On version 3.0 generates an error.
    ports:
      - "80:80"
      - "5443:5443"
    
    volumes:
      - .:/var/www/app
      - ./containers/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  
  db:
    image: mariadb
    
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    
    ports:
      - "3306:3306"  
    volumes:
      - ./containers/mysql/data:/var/lib/mysql
      - ./containers/mysql/my.cnf:/etc/mysql/my.cnf
      
    networks:
      - app-network

  app:
    image: alanoteles/laravel-phpfpm:7.2
    
    # mem_limit: 134217728b   # Available until version 2.1. On version 3.0 generates an error.

    # To run at production environment, comment/change XDEBUG to "false"
    environment:
      CONTAINER_ROLE: app
      APP_ENV: local
      XDEBUG: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
    volumes:
      - ./containers/mysql/data:/var/lib/mysql
      - .:/var/www/app
      - ./containers/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - app-network

    depends_on:
      - db
      - redis
  
  artisan-queue:
    
    image: alanoteles/laravel-phpfpm:7.2
    environment:
      CONTAINER_ROLE: queue
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LARAVEL_HORIZON: "false"
      
    command: "/usr/bin/supervisord --nodaemon --configuration /etc/supervisor/supervisord.conf"
    volumes:
      - ./containers/mysql/data:/var/lib/mysql
      - .:/var/www/app
      - ./containers/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - app-network

    depends_on:
      - db
      - redis

  artisan-scheduler:
    
    image: alanoteles/laravel-phpfpm:7.2
    environment:
      CONTAINER_ROLE: scheduler
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
    volumes:
      - .:/var/www/app
      - ./containers/mysql/data:/var/lib/mysql
      - ./containers/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - app-network

    depends_on:
      - db
      - redis

  redis:
    image: redis
    
    ports:
      - "6379:6379"

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
