version: "3"
services:
  nginx:
    environment:
      LARAVEL_SERVER_NAME: localhost
    image: nginx:stable
    container_name: nginx-www
    links:
      - phpfpm:fpm
    # mem_limit: 134217728b   # Available until version 2.1. On version 3.0 generates an error.
    ports:
      - "80:80"
      - "5443:5443"
    
    volumes:
      - .:/var/www/app
  
  db:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    
    ports:
      - "3306:3306"  
    volumes:
      - ./containers/storage/data:/var/lib/mysql

  phpfpm:
    image: alanoteles/laravel-phpfpm:7.1
    container_name: laravel-phpfpm
    # mem_limit: 134217728b   # Available until version 2.1. On version 3.0 generates an error.

    # To run at production environment, comment/change XDEBUG to "false"
    environment:
      CONTAINER_ROLE: app
      APP_ENV: local
      XDEBUG: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
    volumes:
      - ./containers/storage/data:/var/lib/mysql
      - .:/var/www/app

    depends_on:
      - db
      - redis
  
  artisan-queue:
    container_name: laravel-queue
    image: alanoteles/laravel-phpfpm:7.1
    environment:
      CONTAINER_ROLE: queue
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LARAVEL_HORIZON: "false"
      
    command: "/usr/bin/supervisord --nodaemon --configuration /etc/supervisor/supervisord.conf"
    volumes:
      - ./containers/storage/data:/var/lib/mysql
      - .:/var/www/app
    depends_on:
      - db
      - redis

  artisan-scheduler:
    container_name: laravel-scheduler
    image: alanoteles/laravel-phpfpm:7.1
    environment:
      CONTAINER_ROLE: scheduler
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
    volumes:
      - .:/var/www/app
    depends_on:
      - db
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
